apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaculikovolevevarle.fullname" . }}-bot
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vaculikovolevevarle.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vaculikovolevevarle.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bot
  template:
    metadata:
      labels:
        {{- include "vaculikovolevevarle.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bot
    spec:
      initContainers:
        - name: wait-for-lavalink
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z lavalink.{{ .Values.namespace.name }}.svc.cluster.local 2333; do echo waiting for lavalink; sleep 2; done;']
      containers:
        - name: bot
          image: "{{ .Values.image.bot.repository }}:{{ .Values.image.bot.tag }}"
          imagePullPolicy: {{ .Values.image.bot.pullPolicy }}
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaculikovolevevarle.fullname" . }}-secrets
                  key: BOT_TOKEN
            - name: LAVA_HOST
              value: "lavalink.{{ .Values.namespace.name }}.svc.cluster.local"
            - name: LAVA_PORT
              value: "2333"
            - name: LAVA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaculikovolevevarle.fullname" . }}-secrets
                  key: LAVALINK_PASSWORD
          {{- if .Values.persistence.bot.logs.enabled }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          {{- end }}
          resources:
            {{- toYaml .Values.resources.bot | nindent 12 }}
      {{- if .Values.persistence.bot.logs.enabled }}
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "vaculikovolevevarle.fullname" . }}-bot-logs-pvc
      {{- end }}
