apiVersion: v1
kind: Service
metadata:
  name: lavalink
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vaculikovolevevarle.labels" . | nindent 4 }}
    app.kubernetes.io/component: lavalink
spec:
  type: {{ .Values.service.lavalink.type }}
  ports:
    - port: {{ .Values.service.lavalink.port }}
      targetPort: 2333
      protocol: TCP
      name: lavalink
  selector:
    {{- include "vaculikovolevevarle.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lavalink
