apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "vaculikovolevevarle.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vaculikovolevevarle.labels" . | nindent 4 }}
spec:
  encryptedData:
    BOT_TOKEN: {{ .Values.secrets.botToken | quote }}
    LAVALINK_PASSWORD: {{ .Values.secrets.lavalinkPassword | quote }}
    SPOTIFY_CLIENT_ID: {{ .Values.secrets.spotifyClientId | quote }}
    SPOTIFY_CLIENT_SECRET: {{ .Values.secrets.spotifyClientSecret | quote }}
  template:
    metadata:
      name: {{ include "vaculikovolevevarle.fullname" . }}-secrets
      namespace: {{ .Values.namespace.name }}
    type: Opaque
